// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(IVANContext))]
    [Migration("20250528160741_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1373),
                            Email = "volunteer1@example.com",
                            EmailVerified = true,
                            IsActive = true,
                            PasswordHash = "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1373),
                            Username = "volunteer1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1376),
                            Email = "volunteer2@example.com",
                            EmailVerified = true,
                            IsActive = true,
                            PasswordHash = "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1377),
                            Username = "volunteer2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1379),
                            Email = "admin@example.com",
                            EmailVerified = true,
                            IsActive = true,
                            PasswordHash = "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            RoleId = 4,
                            UpdatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1379),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.VolunteerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BackgroundCheckDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Interests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBackgroundChecked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerHoursCompleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VolunteerProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Láng, Đống Đa",
                            Availability = "Weekends,Evenings",
                            Bio = "Tình nguyện viên nhiệt huyết với 5 năm kinh nghiệm trong các hoạt động cộng đồng.",
                            City = "Hà Nội",
                            Company = "FPT Software",
                            CreatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1437),
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "Đại học",
                            EmergencyContactName = "Nguyen Thi B",
                            EmergencyContactPhone = "0987654322",
                            FirstName = "Nguyen",
                            Gender = "Male",
                            Interests = "Environmental Conservation,Education",
                            IsBackgroundChecked = false,
                            LastName = "Van A",
                            Occupation = "Kỹ sư phần mềm",
                            Phone = "0987654321",
                            Province = "Hà Nội",
                            Skills = "First Aid,Teaching",
                            UpdatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1437),
                            UserId = 1,
                            VolunteerHoursCompleted = 50
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Nguyễn Trãi, Thanh Xuân",
                            Availability = "Weekdays,Evenings",
                            Bio = "Tình nguyện viên năng động, thích tham gia các hoạt động phát triển cộng đồng.",
                            City = "Hà Nội",
                            Company = "VinGroup",
                            CreatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1455),
                            DateOfBirth = new DateTime(1998, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EducationLevel = "Đại học",
                            EmergencyContactName = "Tran Van D",
                            EmergencyContactPhone = "0912345679",
                            FirstName = "Tran",
                            Gender = "Female",
                            Interests = "Community Development,Health",
                            IsBackgroundChecked = false,
                            LastName = "Thi C",
                            Occupation = "Nhân viên marketing",
                            Phone = "0912345678",
                            Province = "Hà Nội",
                            Skills = "Event Management,Public Speaking",
                            UpdatedAt = new DateTime(2025, 5, 28, 16, 7, 41, 297, DateTimeKind.Utc).AddTicks(1455),
                            UserId = 2,
                            VolunteerHoursCompleted = 30
                        });
                });

            modelBuilder.Entity("WebAPI.Data.Entities.VolunteerProfile", b =>
                {
                    b.HasOne("WebAPI.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
